version: "3"
services:
  app:
    container_name: app
    # restart: always
    build: .
    environment: 
      NODE_ENV: "production"
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    # volumes:
    #   - /tmp/mongo/data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: america_fuck_yeah
      MONGO_INITDB_DATABASE: "amfy-iot"